branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/ # regex

language: android

jdk:
  - oraclejdk8

before_install:
    - pip install --user codecov
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

after_success:
  - ./gradlew coveralls
  - codecov

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

jobs:
  include:
    - stage: test
      script: ./gradlew clean testDebugUnitTest jacocoTestReport
    - stage: release
      script: ./gradlew javadocRelease
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
          local_dir: docs/
          on:
            all_branches: true
