branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/ # regex

language: android

jdk:
  - openjdk8

before_install:
    - pip install --user codecov
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport

after_success:
  - ./gradlew coveralls
  - codecov

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository
